# Generated by Django 4.2.7 on 2025-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('importance', models.IntegerField(default=5, help_text='Scale 1-10')),
                ('urgency', models.IntegerField(default=5, help_text='Scale 1-10')),
                ('effort', models.IntegerField(default=5, help_text='Scale 1-10')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of task IDs this task depends on')),
                ('priority_score', models.FloatField(default=0)),
                ('urgency_score', models.FloatField(default=0)),
                ('importance_score', models.FloatField(default=0)),
                ('effort_score', models.FloatField(default=0)),
                ('dependency_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority_score', 'deadline'],
            },
        ),
    ]
