# Generated by Django 4.2.7 on 2025-11-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority_score', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='dependency_score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='effort_score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='importance_score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='urgency_score',
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='effort',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(default=5),
        ),
    ]
